 select NOMBRE_PACIENTE,FECHA_ATENCION,HORA_ATENCION,CONSULTORIO,ID_CONSULTORIO from citas

 SELECT CC.HORA FROM CONSULTORIO_CITA AS CC INNER JOIN 
 CITAS as c ON CC.NOMBRE_CONS=C.CONSULTORIO 
 WHERE   (C.CONSULTORIO='CONSULTORIO 2'AND CC.HORA NOT IN( C.HORA_ATENCION)) 
 and C.ID_CONSULTORIO='ENFERMERIA' and  CONVERT(DATE, C.FECHA_ATENCION,103)='29-10-2021' 
 GROUP BY CC.HORA order by HORA desc


 select * from CONSULTORIO_CITA
 --select * from CITAS



SELECT CC.*
  FROM CONSULTORIO_CITA CC
  LEFT JOIN CITAS C
    ON CC.NOMBRE_CONS = C.CONSULTORIO
 WHERE C.CONSULTORIO='CONSULTORIO 1' and  CONVERT(DATE, C.FECHA_ATENCION,103)='29-10-2021'AND  CC.HORA NOT IN (C.HORA_ATENCION)  

 --Supongamos t1 = Tabla Origen, t2 = Tabla donde están los registros que no queremos. 
 --Trabajaremos con el campo id pero lo pueden substituir por la clave o claves de sus tablas
   select NOMBRE_PACIENTE,FECHA_ATENCION,HORA_ATENCION,CONSULTORIO,ID_CONSULTORIO from citas ORDER BY CONSULTORIO

SELECT * FROM citas   WHERE  ID_CONSULTORIO=''AND CONSULTORIO='' 

--MOSTRAR LAS HORAS QUE NO ESTAS OCUPADAS 
 Select CC.NOMBRE_CONS,CC.HORA,CC.CONSULTORIO from CONSULTORIO_CITA AS CC
 INNER JOIN CITAS AS C ON C.CONSULTORIO=CC.NOMBRE_CONS 
 where not exists (select C.HORA_ATENCION from CITAS AS C where CC.HORA=C.HORA_ATENCION)
 AND (C.ID_CONSULTORIO='ENFERMERIA' AND C.CONSULTORIO='CONSULTORIO 1')
 and  CONVERT(DATE, C.FECHA_ATENCION,103)='29-10-2021' 
 GROUP BY CC.NOMBRE_CONS,CC.HORA,CC.CONSULTORIO ORDER BY CC.HORA
 ---FIN---
 --PARA QUE FUNCIONE NO LAS HORAS NO DEBEN REPETIRSE---

 select NOMBRE_CONS from CONSULTORIO_CITA WHERE CONSULTORIO='MEDICINA' GROUP BY NOMBRE_CONS

 SELECT count(*)  FROM (SELECT DNI FROM CITAS WHERE ID_CONSULTORIO='ENFERMERIA' AND CONSULTORIO='CONSULTORIO 1'  AND CONVERT(DATE,FECHA_ATENCION,103) ='29-10-2021')AS T