--select *  from CONSULTORIO_CITA

SELECT * FROM USER

 select * from CONSULTORIO_CITA
 select * from citas

SELECT COUNT(*) FROM (SELECT HORA_ATENCION  FROM CITAS
 WHERE CONVERT(DATE,FECHA_ATENCION,103)='29/10/2021'AND CONSULTORIO IN('consultorio 1','consultorio 1')AND ID_CONSULTORIO='ENFERMERIA' AND (HORA_ATENCION NOT IN('')OR HORA_ATENCION IS NULL))T

 select FECHA_ATENCION,HORA_ATENCION,CONSULTORIO,ID_CONSULTORIO from CITAS where ID_CONSULTORIO='ENFERMERIA' AND CONSULTORIO IN('consultorio II') AND CONVERT(DATE, FECHA_ATENCION,103)='30-11-2021' 



 SELECT CC.HORA FROM CONSULTORIO_CITA AS CC INNER JOIN 
 CITAS as c ON CC.NOMBRE_CONS=C.CONSULTORIO 
 WHERE C.ID_CONSULTORIO='ENFERMERIA' and  CONVERT(DATE, C.FECHA_ATENCION,103)='30-11-2021' 
 AND (C.CONSULTORIO='CONSULTORIO II'AND CC.HORA NOT IN( C.HORA_ATENCION)) GROUP BY CC.HORA order by HORA desc



 SELECT * FROM CONSULTORIO_CITA WHERE  CONSULTORIO='ENFERMERIA' AND NOMBRE_CONS='CONSULTORIO 1'

 select * from citas
UPDATE citas
SET id_consultorio = 'ENFERMERIA'
WHERE CONSULTORIO='ADICIONAL';


ALTER TABLE dbo.CONSULTORIO_CITA ALTER COLUMN HORA VARCHAR(9);  